language: node_js
node_js:
- "0.12"
- "iojs"
services:
- mongodb
env:
- YIELDB_TEST_URI=mongodb://localhost/yieldb_test

script: "make test-travis"
after_script: "npm install coveralls@2.11.1 && cat ./coverage/lcov.info | coveralls"
